version: "3"

services:
  app:
    build: ./docker
    container_name: modentca-be-app-2
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
  db:
    image: mysql:5.7
    container_name: modentca-be-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
